"$schema" = "https://conductor.build/schemas/settings.repo.schema.json"

[scripts]
setup = ".conductor/setup.sh"
run_mode = "concurrent"

[scripts.run.run-server]
command = ".conductor/run-server.sh"
available_in = [ "local" ]
default = true
icon = "play"

[scripts.run.mailpit]
command = ".conductor/run-mailpit.sh"
available_in = [ "local" ]
icon = "mail"

[scripts.run.tailwind-css]
command = "./scripts/tailwind.sh watch"
icon = "wind"
